### ISSUE TITLE
disclosures/2021-06-29 seems to have a section that wasn't finished

### ISSUE THREAD

**Issue by wschwab** [yearn/yearn-security#37]
Unless `Gro` is some kind of disclosure that I am unaware of, I suspect the ["Third Party Discolsure"](https://github.com/yearn/yearn-security/blob/master/disclosures/2021-06-29.md#third-party-disclosure) is incomplete in the disclosure report for June 29, 2021.

![Yearn_security_incident](https://user-images.githubusercontent.com/31592931/124110484-f239d200-da70-11eb-8a4f-f5b9e4ca9168.png)

**Comment by dtcarls** [comment]
I am not on the team, but "Gro" is the "Gro Protocol" who was informed at 22:25 on the night of the report, which would be before the publication of the disclosure here.

**Comment by lehnberg** [comment]
2nd person raising this feedback, I've submitted PR that fixes it (linked above)
